services:
  # Telemetry Service - Zipkin (More reliable alternative)
  zipkin:
    image: openzipkin/zipkin:3
    container_name: syphon-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"  # Zipkin UI and API
    networks:
      - syphon-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Main Application Service - Runs last for proper dependency order
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - VERSION=${VERSION:-0.2.0}
    container_name: syphon-app
    restart: unless-stopped
    environment:
      # Core application environment
      - NODE_ENV=${NODE_ENV:-production}
      - VERSION=${VERSION:-0.2.0}
      - BRANCH=${BRANCH:-main}
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      
      # Database configuration - Using external Neon DB
      - DATABASE_URL=${DATABASE_URL}
      
      # Authentication configuration
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL:-/dashboard}
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL:-/dashboard}
      
      # OpenTelemetry configuration - Local Zipkin service
      - OTEL_SDK_DISABLED=${OTEL_SDK_DISABLED:-false}
      - OTEL_SERVICE_NAME=syphon-app
      - OTEL_SERVICE_VERSION=${VERSION:-0.2.0}
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_RESOURCE_ATTRIBUTES=service.name=syphon-app,service.version=${VERSION:-0.2.0},deployment.environment=${NODE_ENV:-production}
      
      # Additional OpenTelemetry settings for robustness
      - OTEL_EXPORTER_OTLP_TIMEOUT=10000
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip
      - OTEL_BSP_MAX_EXPORT_BATCH_SIZE=512
      - OTEL_BSP_EXPORT_TIMEOUT=30000
      - OTEL_BSP_SCHEDULE_DELAY=5000
    ports:
      - "3001:3001"
    depends_on:
      zipkin:
        condition: service_healthy
    networks:
      - syphon-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # Enhanced logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes: {}

networks:
  syphon-network:
    driver: bridge