# Nixpacks configuration for Syphon deployment on Dokploy
# Removed explicit providers as Nixpacks should autodetect with a package.json
# If autodection fails, we'll re-add it.

[variables]
# Node.js configuration
NODE_VERSION = "20"
NODE_ENV = "production"
# Temporarily removed NPM_CONFIG_CACHE and NPM_CONFIG_PRODUCTION to simplify

# Next.js configuration
NEXT_TELEMETRY_DISABLED = "1"

[phases.build]
dependsOn = ["install"]
cmds = [
    "npx prisma generate",
    "npm run build"
]

[phases.install]
cmds = [
    "npm ci" # 'ci' implies installing prod dependencies and dev dependencies for development context
            # Removed --include=dev as 'ci' often includes dev by default or for its specific purpose
]

[start]
cmd = "npm start"

# Health check configuration
[healthcheck]
path = "/api/health"