version: '3.8'

services:
  # Production Jaeger setup
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    container_name: syphon-jaeger-prod
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_DISABLED=false
      # Production memory settings
      - MEMORY_MAX_TRACES=50000
      # Enable metrics
      - METRICS_BACKEND=prometheus
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    volumes:
      # Persist trace data (optional)
      - jaeger_data:/tmp
    networks:
      - syphon-production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: syphon-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - syphon-production

volumes:
  jaeger_data:
    driver: local
  prometheus_data:
    driver: local

networks:
  syphon-production:
    driver: bridge