global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger-all-in-one:14269']
    metrics_path: /metrics

  # Syphon application metrics (if you add them later)
  # - job_name: 'syphon-app'
  #   static_configs:
  #     - targets: ['syphon-app:3000']
  #   metrics_path: /api/metrics